### ISSUE TITLE
Ruby 2.3.5 + Rails 4.2.10 exceptions

### ISSUE THREAD

**Issue by mikhailov** [ruby/syck#24]
Syck 1.3.0
Ruby 2.3.5
Rails 4.2.10 (blank application)

While trying to bump an application (Rails 3 to Rails 4) I found the parsing issues in Rails 4.2.10, I can reproduce it on a blank Rails 4 app, although running it in `irb` (without Rails) it works perfectly. The issue is not necessarly in this gem, but can be in conjuction with active_support.

```
rbenv local 2.3.5
gem install rails -v 4.2.10
rails new yaml_test
cd yaml_test
# add gem 'syck' to Gemfile
bundle install
rails console

puts Syck.load %Q(
--- test_key:
title: Test Key
definition: !ruby/object:OpenStruct
  position: 123
)

NoMethodError: undefined method `key?' for nil:NilClass
from /Users/.../.rbenv/versions/2.3.5/lib/ruby/2.3.0/ostruct.rb:190:in `respond_to_missing?'
from /Users/.../.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/syck-1.3.0/lib/syck.rb:142:in `transfer'
from /Users/.../.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/syck-1.3.0/lib/syck.rb:142:in `node_import'
from /Users/.../.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/syck-1.3.0/lib/syck.rb:142:in `load'
from /Users/.../.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/syck-1.3.0/lib/syck.rb:142:in `load'
from (irb):8
```

**Comment by mikhailov** [comment]
related to https://github.com/ruby/psych/issues/263?

**Comment by mikhailov** [comment]
Same issue reported as a bug in Ruby: https://bugs.ruby-lang.org/issues/11966. While trying to reproduce, this fixed in plain Ruby script (Ruby version 2.3.5), but fail in conjuction with Rails

**Comment by mikhailov** [comment]
it has been fixed in 2.4 but not ported to 2.3 https://bugs.ruby-lang.org/issues/13358

**Comment by kirs** [comment]
<details>
<summary>Environment</summary>

```
$ ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin17]
```

```
$ bundle list
Gems included by the bundle:
  * activesupport (5.1.4)
  * bundler (1.16.0)
  * concurrent-ruby (1.0.5)
  * i18n (0.9.1)
  * minitest (5.10.3)
  * syck (1.3.0)
  * thread_safe (0.3.6)
  * tzinfo (1.2.4)
```

</details>

**Works:**

```ruby
require 'syck'
puts Syck.load %Q(
--- test_key:
title: Test Key
definition: !ruby/object:OpenStruct
  position: 123
)
```

**Fails:**

```ruby
require 'syck'
require 'json'

puts Syck.load %Q(
--- test_key:
title: Test Key
definition: !ruby/object:OpenStruct
  position: 123
)
```

```
/opt/rubies/2.3.3/lib/ruby/2.3.0/ostruct.rb:186:in `respond_to_missing?': undefined method `key?' for nil:NilClass (NoMethodError)
        from /Users/kir/.gem/ruby/2.3.3/gems/syck-1.3.0/lib/syck.rb:142:in `transfer'
        from /Users/kir/.gem/ruby/2.3.3/gems/syck-1.3.0/lib/syck.rb:142:in `node_import'
        from /Users/kir/.gem/ruby/2.3.3/gems/syck-1.3.0/lib/syck.rb:142:in `load'
        from /Users/kir/.gem/ruby/2.3.3/gems/syck-1.3.0/lib/syck.rb:142:in `load'
        from repro.rb:3:in `<main>'
```

I wouldn't blame Rails or ActiveSupport, they just include `json` which somehow makes sych / openstruct crash.

I'm not sure how `json` related to `openstruct` here, but I could come up with a shitty patch that could unblock you (use at your own risk):

```ruby
require 'syck'
require "json"

module OStructPatch
  def respond_to_missing?(*)
    @table ||= {}
    super
  end
end
OpenStruct.prepend(OStructPatch)

puts Syck.load %Q(
--- test_key:
title: Test Key
definition: !ruby/object:OpenStruct
  position: 123
)
```

**Comment by mikhailov** [comment]
@kirs 👍 it works!
